---
# tasks file for ntp
- assert:
    msg: "aplicando ntp client"
    that: 
      - client is defined
    quiet: true  

- name:  Configuracoes de ntp client
  import_tasks: client.yml
  when: 
    - ansible_os_family == "Debian"
    - client is defined

- assert:
    msg: "aplicando ntp server"
    that: 
      - server is defined
    quiet: true  

- name:  Configuracoes de ntpd
  import_tasks: server.yml
  when: 
    - ansible_os_family == "Debian"
    - server is defined   